version: '3.3'
services:
    eve:
        build: ./eve
        ports:
            - "5000:5000"
        network_mode: bridge
        environment:
            - PYTHONUNBUFFERED=0 
        volumes:
            - ./eve/code:/code
        entrypoint:
            - python
            - -u
            - run.py
        secrets:
            - totp_master

secrets:
    totp_master:
        file: ./eve/secrets/TOTP_MASTER
